import { useState } from "react";
import { useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Breakdown, Lifestyle, HousingType, TravelerType, WorkStyle } from "../data/costs";

interface LeadModalProps {
  result: {
    total: number;
    breakdown: Breakdown;
    country: string;
    countryName: string;
    city?: string;
    lifestyle: Lifestyle;
    stayLength: number;
    housingType: HousingType;
    travelerType: TravelerType;
    workStyle: WorkStyle;
  };
  onClose: () => void;
}

export function LeadModal({ result, onClose }: LeadModalProps) {
  const [email, setEmail] = useState("");
  const [consent, setConsent] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const submitLead = useMutation(api.leads.submitLead);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !consent) return;

    setIsLoading(true);
    setError(null);

    try {
      // Generate a simple identifier for rate limiting
      const identifier = btoa(navigator.userAgent + window.screen.width);

      await submitLead({
        email,
        consent,
        country: result.country,
        city: result.city,
        lifestyle: result.lifestyle,
        stayLength: result.stayLength,
        housingType: result.housingType,
        travelerType: result.travelerType,
        workStyle: result.workStyle,
        totalCost: result.total,
        breakdown: result.breakdown,
        identifier,
      });

      setSubmitted(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to submit. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    // Generate a simple PDF-like content (in real app, this would be a proper PDF)
    const content = `
RELOCATION PLAN: ${result.countryName}${result.city ? ` - ${result.city}` : ""}
Generated by TravelToolHub

SUMMARY
-------
Lifestyle: ${result.lifestyle.charAt(0).toUpperCase() + result.lifestyle.slice(1)}
Housing: ${result.housingType.toUpperCase()}
Traveler: ${result.travelerType.charAt(0).toUpperCase() + result.travelerType.slice(1)}
Stay Length: ${result.stayLength} months
Work Style: ${result.workStyle.charAt(0).toUpperCase() + result.workStyle.slice(1)}

MONTHLY COST BREAKDOWN
----------------------
Rent: $${result.breakdown.rent}
Food: $${result.breakdown.food}
Transport: $${result.breakdown.transport}
Utilities: $${result.breakdown.utilities}
Internet/SIM: $${result.breakdown.internet}
Health/Insurance: $${result.breakdown.health}
Fun/Misc: $${result.breakdown.fun}

TOTAL: $${result.total}/month

---
Visit TravelToolHub.com for more travel tools and resources.
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `relocation-plan-${result.country}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
      <div className="w-full max-w-md bg-slate-900/95 backdrop-blur-2xl border border-slate-700/50 rounded-2xl p-6 shadow-2xl animate-slide-up">
        {!submitted ? (
          <>
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-white">Get Your Relocation Plan</h3>
              <button
                onClick={onClose}
                className="p-2 text-slate-400 hover:text-white transition-colors rounded-lg hover:bg-slate-800/50"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            {error && (
              <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400 text-sm">
                {error}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Email Address <span className="text-teal-400">*</span>
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  placeholder="your@email.com"
                  className="w-full px-4 py-3 bg-slate-800/50 border border-slate-700/50 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-teal-500/50 focus:border-teal-500/50 transition-all"
                />
              </div>

              <label className="flex items-start gap-3 cursor-pointer group">
                <input
                  type="checkbox"
                  checked={consent}
                  onChange={(e) => setConsent(e.target.checked)}
                  className="mt-1 w-5 h-5 rounded border-slate-600 bg-slate-800 text-teal-500 focus:ring-teal-500/50 focus:ring-offset-0 cursor-pointer"
                />
                <span className="text-sm text-slate-400 group-hover:text-slate-300 transition-colors">
                  I agree to receive the relocation plan and occasional travel tool updates. <span className="text-teal-400">*</span>
                </span>
              </label>

              <p className="text-xs text-slate-500">
                We respect your privacy. Read our{" "}
                <a href="#privacy" className="text-teal-400 hover:underline">
                  Privacy Policy
                </a>
                .
              </p>

              <button
                type="submit"
                disabled={!email || !consent || isLoading}
                className="w-full py-3.5 bg-gradient-to-r from-teal-600 to-teal-500 hover:from-teal-500 hover:to-teal-400 text-white font-semibold rounded-xl shadow-lg shadow-teal-500/20 transition-all transform hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                {isLoading ? (
                  <span className="inline-flex items-center gap-2">
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    Submitting...
                  </span>
                ) : (
                  "Get My Plan"
                )}
              </button>
            </form>
          </>
        ) : (
          <div className="text-center py-4">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-teal-500/20 flex items-center justify-center">
              <svg className="w-8 h-8 text-teal-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h3 className="text-xl font-bold text-white mb-2">Success!</h3>
            <p className="text-slate-400 mb-6">Your relocation plan is ready.</p>

            <div className="space-y-3">
              <button
                onClick={handleDownload}
                className="w-full py-3.5 bg-gradient-to-r from-teal-600 to-teal-500 hover:from-teal-500 hover:to-teal-400 text-white font-semibold rounded-xl shadow-lg shadow-teal-500/20 transition-all transform hover:scale-[1.02] active:scale-[0.98] flex items-center justify-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Download PDF
              </button>

              <a
                href="https://traveltoolhub.com"
                target="_blank"
                rel="noopener noreferrer"
                className="block w-full py-3 bg-slate-800/50 hover:bg-slate-700/50 border border-slate-700/50 text-slate-300 font-medium rounded-xl transition-all hover:text-white text-center"
              >
                Open TravelToolHub
              </a>

              <button
                onClick={onClose}
                className="w-full py-3 text-slate-400 hover:text-white transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
